name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - deployment # Triển khai khi có commit lên nhánh deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOOKSTORE_ELYSIA }}
          channelId: live # Đảm bảo deploy lên production
          projectId: bookstore-elysia
